apiVersion: v1
kind: Secret
metadata:
  name: middleware-secret
  namespace: {{ .Values.namespace.name }}
  labels:
      {{- include "mw-kube-agent.labels" . | nindent 4 }}
type: Opaque

data:
  api-key: {{ .Values.mw.apiKey | b64enc | quote }}