apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{.Values.namespace.name}}
  labels:
    {{- include "mw-kube-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.targetPort }}
      name: grpc
    - port: {{ .Values.service.grpc2.port }}
      targetPort: {{ .Values.service.grpc2.targetPort }}
      name: grpc2
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      name: http
    - port: {{ .Values.service.fluent.port }}
      targetPort: {{ .Values.service.fluent.targetPort }}
      name: fluent
  selector:
    {{- include ".Values.selectorLabels" . | nindent 4 }}
